import AdminNav from "@/components/admin/admin-nav";
import { requirePlatformContext } from "@/lib/admin/context";

import { updatePlatformCase } from "./actions";

type PageProps = { searchParams: Promise<{ updated?: string; error?: string }> };

export default async function AdminCasesPage({ searchParams }: PageProps) {
  const query = await searchParams;
  const { supabase } = await requirePlatformContext();
  const { data: cases, error } = await supabase.from("platform_cases").select("id, case_type, status, priority, subject, description, resolution_summary, operator_id, booking_id, created_at, updated_at").order("updated_at", { ascending: false }).limit(200);
  if (error) throw new Error(`Unable to load platform cases: ${error.message}`);

  return <main className="min-h-screen bg-[#FCFBF8] text-[#0B1F33]"><AdminNav/><div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><p className="text-sm font-semibold text-[#14B8A6]">Case management</p><h1 className="mt-2 text-4xl font-semibold tracking-tight">Casi operativi</h1>{query.updated?<div className="mt-5 rounded-2xl border border-[#14B8A6]/30 bg-[#14B8A6]/10 p-4 text-sm">Caso aggiornato.</div>:null}{query.error?<div className="mt-5 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{query.error}</div>:null}<div className="mt-6 space-y-4">{(cases??[]).map((item)=><article key={item.id} className="rounded-3xl border border-[#DEE5E8] bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wide text-[#14B8A6]">{item.case_type} · {item.priority}</p><h2 className="mt-2 text-lg font-semibold">{item.subject}</h2><p className="mt-2 text-sm text-[#64748B]">{item.description??"Nessuna descrizione"}</p></div><span className="rounded-full bg-[#F1F5F4] px-3 py-2 text-xs font-semibold">{item.status}</span></div><form action={updatePlatformCase} className="mt-5 grid gap-3 border-t border-[#DEE5E8] pt-4 md:grid-cols-[1fr_1fr_2fr_auto] md:items-end"><input type="hidden" name="case_id" value={item.id}/><div><label className="mb-1 block text-xs font-medium">Stato</label><select name="status" defaultValue={item.status} className="w-full rounded-xl border border-[#DEE5E8] px-3 py-2 text-sm">{["OPEN","IN_PROGRESS","WAITING","RESOLVED","CLOSED"].map((v)=><option key={v}>{v}</option>)}</select></div><div><label className="mb-1 block text-xs font-medium">Priorità</label><select name="priority" defaultValue={item.priority} className="w-full rounded-xl border border-[#DEE5E8] px-3 py-2 text-sm">{["LOW","NORMAL","HIGH","URGENT"].map((v)=><option key={v}>{v}</option>)}</select></div><div><label className="mb-1 block text-xs font-medium">Risoluzione</label><input name="resolution_summary" defaultValue={item.resolution_summary??""} className="w-full rounded-xl border border-[#DEE5E8] px-3 py-2 text-sm" placeholder="Obbligatoria per resolved/closed"/></div><button className="rounded-xl bg-[#0B1F33] px-4 py-2 text-sm font-semibold text-white">Salva</button></form></article>)}{(cases??[]).length===0?<p className="rounded-3xl bg-white p-8 text-sm text-[#64748B]">Nessun caso accessibile al tuo ruolo.</p>:null}</div></div></main>;
}
