import AdminNav from "@/components/admin/admin-nav";
import { requirePlatformContext } from "@/lib/admin/context";

export default async function AdminPrivacyPage() {
  const { supabase } = await requirePlatformContext(["SUPER_ADMIN"]);
  const { data: requests, error } = await supabase.from("privacy_requests").select("id, requester_name_snapshot, requester_email_snapshot, request_type, status, identity_verification_status, scope, received_at, response_due_at, resolved_at, decision_summary").order("received_at", { ascending: false }).limit(200);
  if (error) throw new Error(`Unable to load privacy requests: ${error.message}`);

  return <main className="min-h-screen bg-[#FCFBF8] text-[#0B1F33]"><AdminNav/><div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><p className="text-sm font-semibold text-[#14B8A6]">Data governance</p><h1 className="mt-2 text-4xl font-semibold tracking-tight">Privacy requests</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[#64748B]">Registro operativo delle richieste privacy. La base dati supporta il workflow; le decisioni legali e le scadenze effettive non vengono dedotte automaticamente dal software.</p><section className="mt-6 overflow-hidden rounded-3xl border border-[#DEE5E8] bg-white shadow-sm"><div className="divide-y divide-[#DEE5E8]">{(requests??[]).map((request)=><article key={request.id} className="grid gap-4 p-5 lg:grid-cols-[1.2fr_1fr_1fr_1fr]"><div><p className="font-semibold">{request.requester_name_snapshot}</p><p className="mt-1 text-xs text-[#64748B]">{request.requester_email_snapshot}</p></div><div className="text-sm"><p>{request.request_type}</p><p className="mt-1 text-xs text-[#64748B]">Identity: {request.identity_verification_status}</p></div><span className="w-fit rounded-full bg-[#F1F5F4] px-3 py-2 text-xs font-semibold">{request.status}</span><div className="text-xs text-[#64748B]"><p>Ricevuta: {new Date(request.received_at).toLocaleDateString("it-IT")}</p><p className="mt-1">Due: {request.response_due_at ? new Date(request.response_due_at).toLocaleDateString("it-IT") : "da definire"}</p></div></article>)}{(requests??[]).length===0?<div className="p-10 text-center text-sm text-[#64748B]">Nessuna richiesta privacy.</div>:null}</div></section></div></main>;
}
