export type MarketplaceBoat = {
  id: string;
  slug: string;
  name: string;
  operator_id: string;
  operator_name: string | null;
  boat_type_id: string | null;
  boat_type_name: string | null;
  location_id: string | null;
  location_name: string | null;
  city: string | null;
  administrative_area: string | null;
  latitude: number | null;
  longitude: number | null;
  manufacturer: string | null;
  model: string | null;
  manufacture_year: number | null;
  length_m: number | null;
  passenger_limit: number | null;
  license_required: boolean | null;
  short_description: string | null;
  cover_storage_path: string | null;
  from_price_cents: number | null;
  base_duration_minutes: number | null;
  rating: number | null;
  review_count: number | null;
  available: boolean;
  cover_url?: string | null;
};

export type PublicBoatDetail = {
  id: string;
  operator_id: string;
  primary_location_id: string | null;
  boat_type_id: string | null;
  name: string;
  slug: string;
  short_description: string | null;
  description: string | null;
  manufacturer: string | null;
  model: string | null;
  manufacture_year: number | null;
  length_m: number | null;
  beam_m: number | null;
  draft_m: number | null;
  technical_passenger_capacity: number | null;
  operator_passenger_limit: number | null;
  cabins: number | null;
  berths: number | null;
  bathrooms: number | null;
  engine_count: number | null;
  engine_manufacturer: string | null;
  engine_model: string | null;
  engine_installation: string | null;
  engine_fuel_type: string | null;
  engine_power_kw: number | null;
  engine_power_hp: number | null;
  engine_displacement_cc: number | null;
  max_speed_knots: number | null;
  license_required: boolean | null;
};
